export enum Control {
    LookY = "CONTROL_LOOK_Y",
    LookX = "CONTROL_LOOK_X",
    MoveLeft = "CONTROL_MOVE_LEFT",
    MoveRight = "CONTROL_MOVE_RIGHT",
    MoveForwardOnFoot = "CONTROL_MOVE_FORWARD_ON_FOOT",
    MoveBackwardOnFoot = "CONTROL_MOVE_BACKWARD_ON_FOOT",
    MoveForwardInCar = "CONTROL_MOVE_FORWARD_IN_CAR",
    MoveBackwardInCar = "CONTROL_MOVE_BACKWARD_IN_CAR",
    Fire = "CONTROL_FIRE",
    NextWeapon = "CONTROL_NEXT_WEAPON",
    PreviousWeapon = "CONTROL_PREVIOUS_WEAPON",
    Aim = "CONTROL_AIM",
    Sprint = "CONTROL_SPRINT",
    ZoomIn = "CONTROL_ZOOM_IN",
    ZoomOut = "CONTROL_ZOOM_OUT",
    EnterExit = "CONTROL_ENTER_EXIT",
    ChangeCamera = "CONTROL_CHANGE_CAMERA",
    Jump = "CONTROL_JUMP",
    LookBehind = "CONTROL_LOOK_BEHIND",
    Radio = "CONTROL_RADIO",
    Horn = "CONTROL_HORN",
    SubMission = "CONTROL_SUB_MISSION",
    Handbrake = "CONTROL_HANDBRAKE",
}
